# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Hooks
  items:
    - label: 'useCallback'
      link: '/usage/useCallback'
    - label: 'useContext'
      link: '/usage/useContext'
    - label: 'useEffect'
      link: '/usage/useEffect
    - label: 'useLayoutEffect'
      link: '/usage/useLayoutEffect'
    - label: 'useMemo'
      link: '/usage/useMemo'
    - label: 'useReducer'
      link: '/usage/useReducer
    - label: 'useRef'
      link: '/usage/useRef'
    - label: 'useState'
      link: '/usage/useState'  
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/jpedroschmitz/rocketdocs
